### ISSUE TITLE
database migration failed

### ISSUE THREAD

**Issue by hijak** [hashicorp/boundary#2349]
Hi i updated (0.10.0) via yum but am unable to start the service without a db migration which fails:
```
[root@bastion01 ~]# boundary database migrate -config /etc/boundary.hcl 
{"id":"2wDjWNR1F5","source":"https://hashicorp.com/boundary/bastion01.prd.TLD/boundary-database-migrate","specversion":"1.0","type":"system","data":{"version":"v0.1","op":"github.com/hashicorp/boundary/internal/observability/event.(*HclogLoggerAdapter).writeEvent","data":{"@original-log-level":"none","@original-log-name":"aws","msg":"configuring client automatic mTLS"}},"datacontentype":"application/cloudevents","time":"2022-08-11T12:12:27.01721969+02:00"}
{"id":"zmK1HzTdgk","source":"https://hashicorp.com/boundary/bastion01.prd.TLD/boundary-database-migrate","specversion":"1.0","type":"system","data":{"version":"v0.1","op":"github.com/hashicorp/boundary/internal/observability/event.(*HclogLoggerAdapter).writeEvent","data":{"@original-log-level":"none","@original-log-name":"aws","args":["/tmp/198135332/boundary-plugin-host-aws.gz"],"msg":"starting plugin","path":"/tmp/198135332/boundary-plugin-host-aws.gz"}},"datacontentype":"application/cloudevents","time":"2022-08-11T12:12:27.040366907+02:00"}
{"id":"CDl5AezqRk","source":"https://hashicorp.com/boundary/bastion01.prd.TLD/boundary-database-migrate","specversion":"1.0","type":"system","data":{"version":"v0.1","op":"github.com/hashicorp/boundary/internal/observability/event.(*HclogLoggerAdapter).writeEvent","data":{"@original-log-level":"none","@original-log-name":"aws","msg":"plugin started","path":"/tmp/198135332/boundary-plugin-host-aws.gz","pid":2843753}},"datacontentype":"application/cloudevents","time":"2022-08-11T12:12:27.041835792+02:00"}
{"id":"23Fd4tBi8l","source":"https://hashicorp.com/boundary/bastion01.prd.TLD/boundary-database-migrate","specversion":"1.0","type":"system","data":{"version":"v0.1","op":"github.com/hashicorp/boundary/internal/observability/event.(*HclogLoggerAdapter).writeEvent","data":{"@original-log-level":"none","@original-log-name":"aws","msg":"waiting for RPC address","path":"/tmp/198135332/boundary-plugin-host-aws.gz"}},"datacontentype":"application/cloudevents","time":"2022-08-11T12:12:27.041967976+02:00"}
{"id":"t2UtSbEwlT","source":"https://hashicorp.com/boundary/bastion01.prd.TLD/boundary-database-migrate","specversion":"1.0","type":"system","data":{"version":"v0.1","op":"github.com/hashicorp/boundary/internal/observability/event.(*HclogLoggerAdapter).writeEvent","data":{"@original-log-level":"none","@original-log-name":"aws.boundary-plugin-host-aws.gz","msg":"configuring server automatic mTLS","timestamp":"2022-08-11T12:12:27.048+0200"}},"datacontentype":"application/cloudevents","time":"2022-08-11T12:12:27.051652254+02:00"}
{"id":"oAFr5Fgykl","source":"https://hashicorp.com/boundary/bastion01.prd.TLD/boundary-database-migrate","specversion":"1.0","type":"system","data":{"version":"v0.1","op":"github.com/hashicorp/boundary/internal/observability/event.(*HclogLoggerAdapter).writeEvent","data":{"@original-log-level":"none","@original-log-name":"aws","msg":"using plugin","version":1}},"datacontentype":"application/cloudevents","time":"2022-08-11T12:12:27.071383708+02:00"}
{"id":"cPch05q4rO","source":"https://hashicorp.com/boundary/bastion01.prd.TLD/boundary-database-migrate","specversion":"1.0","type":"system","data":{"version":"v0.1","op":"github.com/hashicorp/boundary/internal/observability/event.(*HclogLoggerAdapter).writeEvent","data":{"@original-log-level":"none","@original-log-name":"aws.boundary-plugin-host-aws.gz","address":"/tmp/plugin4191081567","msg":"plugin address","network":"unix","timestamp":"2022-08-11T12:12:27.071+0200"}},"datacontentype":"application/cloudevents","time":"2022-08-11T12:12:27.071556204+02:00"}
{"id":"IQmjeYTzm2","source":"https://hashicorp.com/boundary/bastion01.prd.TLD/boundary-database-migrate","specversion":"1.0","type":"system","data":{"version":"v0.1","op":"github.com/hashicorp/boundary/internal/observability/event.(*HclogLoggerAdapter).writeEvent","data":{"@original-log-level":"none","@original-log-name":"aws.stdio","msg":"waiting for stdio data"}},"datacontentype":"application/cloudevents","time":"2022-08-11T12:12:27.101386232+02:00"}
{"id":"2wskOah8s5","source":"https://hashicorp.com/boundary/bastion01.prd.TLD/boundary-database-migrate","specversion":"1.0","type":"system","data":{"version":"v0.1","op":"github.com/hashicorp/boundary/internal/observability/event.(*HclogLoggerAdapter).writeEvent","data":{"@original-log-level":"none","@original-log-name":"aws.stdio","err":{},"msg":"received EOF, stopping recv loop"}},"datacontentype":"application/cloudevents","time":"2022-08-11T12:12:27.10232096+02:00"}
{"id":"ocWb3s6n5R","source":"https://hashicorp.com/boundary/bastion01.prd.TLD/boundary-database-migrate","specversion":"1.0","type":"system","data":{"version":"v0.1","op":"github.com/hashicorp/boundary/internal/observability/event.(*HclogLoggerAdapter).writeEvent","data":{"@original-log-level":"none","@original-log-name":"aws","msg":"plugin process exited","path":"/tmp/198135332/boundary-plugin-host-aws.gz","pid":2843753}},"datacontentype":"application/cloudevents","time":"2022-08-11T12:12:27.103074512+02:00"}
{"id":"s5swA4wAOW","source":"https://hashicorp.com/boundary/bastion01.prd.TLD/boundary-database-migrate","specversion":"1.0","type":"system","data":{"version":"v0.1","op":"github.com/hashicorp/boundary/internal/observability/event.(*HclogLoggerAdapter).writeEvent","data":{"@original-log-level":"none","@original-log-name":"aws","msg":"plugin exited"}},"datacontentype":"application/cloudevents","time":"2022-08-11T12:12:27.103160544+02:00"}
{"id":"Nno42OYF7f","source":"https://hashicorp.com/boundary/bastion01.prd.TLD/boundary-database-migrate","specversion":"1.0","type":"error","data":{"error":"postgres.(Postgres).Run: migration failed, on line 0: -- drop constraint so we can migrate enm values\n  alter table credential_purpose_enm\n    drop constraint only_predefined_credential_purposes_allowed;\n\n  -- update egress to injected_application\n  update credential_purpose_enm\n     set name = 'injected_application'\n   where name = 'egress';\n\n  -- update application to brokered\n  update credential_purpose_enm\n     set name = 'brokered'\n   where name = 'application';\n\n  -- delete ingress as it will no longer be used\n  delete from credential_purpose_enm\n   where name = 'ingress';\n\n  -- Add new constraint that only allows 'brokered' and new 'injected_application'\n  -- This replaces the constraint defined in 10/03_credential.up.sql\n  alter table credential_purpose_enm\n    add constraint only_predefined_credential_purposes_allowed\n      check (\n        name in (\n          'brokered',\n          'injected_application'\n        )\n      );\n\n  -- update comment on table   \n  comment on table credential_purpose_enm is\n    'credential_purpose_enm is an enumeration table for credential purposes. '\n    'It contains rows for representing the brokered, and injected_application credential purposes.';: immutable column: target_credential_library.credential_purpose: integrity violation: error #1003","error_fields":{"Code":1003,"Msg":"migration failed, on line 0: -- drop constraint so we can migrate enm values\n  alter table credential_purpose_enm\n    drop constraint only_predefined_credential_purposes_allowed;\n\n  -- update egress to injected_application\n  update credential_purpose_enm\n     set name = 'injected_application'\n   where name = 'egress';\n\n  -- update application to brokered\n  update credential_purpose_enm\n     set name = 'brokered'\n   where name = 'application';\n\n  -- delete ingress as it will no longer be used\n  delete from credential_purpose_enm\n   where name = 'ingress';\n\n  -- Add new constraint that only allows 'brokered' and new 'injected_application'\n  -- This replaces the constraint defined in 10/03_credential.up.sql\n  alter table credential_purpose_enm\n    add constraint only_predefined_credential_purposes_allowed\n      check (\n        name in (\n          'brokered',\n          'injected_application'\n        )\n      );\n\n  -- update comment on table   \n  comment on table credential_purpose_enm is\n    'credential_purpose_enm is an enumeration table for credential purposes. '\n    'It contains rows for representing the brokered, and injected_application credential purposes.';","Op":"postgres.(Postgres).Run","Wrapped":{"Code":1003,"Msg":"immutable column: target_credential_library.credential_purpose","Op":"","Wrapped":null}},"id":"e_ITVsq4g33K","version":"v0.1","op":"postgres.(Postgres).Run"},"datacontentype":"application/cloudevents","time":"2022-08-11T12:12:27.25653352+02:00"}
{"id":"dduUrQgYgk","source":"https://hashicorp.com/boundary/bastion01.prd.TLD/boundary-database-migrate","specversion":"1.0","type":"error","data":{"error":"postgres.(Postgres).setVersion: unknown, unknown: error #0: ERROR: current transaction is aborted, commands ignored until end of transaction block (SQLSTATE 25P02)","error_fields":{"Code":0,"Msg":"","Op":"postgres.(Postgres).setVersion","Wrapped":{"Severity":"ERROR","Code":"25P02","Message":"current transaction is aborted, commands ignored until end of transaction block","Detail":"","Hint":"","Position":0,"InternalPosition":0,"InternalQuery":"","Where":"","SchemaName":"","TableName":"","ColumnName":"","DataTypeName":"","ConstraintName":"","File":"postgres.c","Line":1682,"Routine":"exec_bind_message"}},"id":"e_OYx6YX3oBy","version":"v0.1","op":"postgres.(Postgres).setVersion"},"datacontentype":"application/cloudevents","time":"2022-08-11T12:12:27.257584522+02:00"}
{"id":"yFj9uY26zn","source":"https://hashicorp.com/boundary/bastion01.prd.TLD/boundary-database-migrate","specversion":"1.0","type":"error","data":{"error":"postgres.(Postgres).Run: postgres.(Postgres).setVersion: unknown, unknown: error #0: ERROR: current transaction is aborted, commands ignored until end of transaction block (SQLSTATE 25P02)","error_fields":{"Code":0,"Msg":"","Op":"postgres.(Postgres).Run","Wrapped":{"Code":0,"Msg":"","Op":"postgres.(Postgres).setVersion","Wrapped":{"Severity":"ERROR","Code":"25P02","Message":"current transaction is aborted, commands ignored until end of transaction block","Detail":"","Hint":"","Position":0,"InternalPosition":0,"InternalQuery":"","Where":"","SchemaName":"","TableName":"","ColumnName":"","DataTypeName":"","ConstraintName":"","File":"postgres.c","Line":1682,"Routine":"exec_bind_message"}}},"id":"e_Oc5hNYhcUn","version":"v0.1","op":"postgres.(Postgres).Run"},"datacontentype":"application/cloudevents","time":"2022-08-11T12:12:27.257765962+02:00"}
{"id":"otuSOfK0Db","source":"https://hashicorp.com/boundary/bastion01.prd.TLD/boundary-database-migrate","specversion":"1.0","type":"error","data":{"error":"postgres.(Postgres).setVersion: unknown, unknown: error #0: ERROR: current transaction is aborted, commands ignored until end of transaction block (SQLSTATE 25P02)","error_fields":{"Code":0,"Msg":"","Op":"postgres.(Postgres).setVersion","Wrapped":{"Severity":"ERROR","Code":"25P02","Message":"current transaction is aborted, commands ignored until end of transaction block","Detail":"","Hint":"","Position":0,"InternalPosition":0,"InternalQuery":"","Where":"","SchemaName":"","TableName":"","ColumnName":"","DataTypeName":"","ConstraintName":"","File":"postgres.c","Line":1682,"Routine":"exec_bind_message"}},"id":"e_itYS9l1kig","version":"v0.1","op":"postgres.(Postgres).setVersion"},"datacontentype":"application/cloudevents","time":"2022-08-11T12:12:27.26063903+02:00"}
{"id":"wetyQK73aN","source":"https://hashicorp.com/boundary/bastion01.prd.TLD/boundary-database-migrate","specversion":"1.0","type":"error","data":{"error":"postgres.(Postgres).Run: postgres.(Postgres).setVersion: unknown, unknown: error #0: ERROR: current transaction is aborted, commands ignored until end of transaction block (SQLSTATE 25P02)","error_fields":{"Code":0,"Msg":"","Op":"postgres.(Postgres).Run","Wrapped":{"Code":0,"Msg":"","Op":"postgres.(Postgres).setVersion","Wrapped":{"Severity":"ERROR","Code":"25P02","Message":"current transaction is aborted, commands ignored until end of transaction block","Detail":"","Hint":"","Position":0,"InternalPosition":0,"InternalQuery":"","Where":"","SchemaName":"","TableName":"","ColumnName":"","DataTypeName":"","ConstraintName":"","File":"postgres.c","Line":1682,"Routine":"exec_bind_message"}}},"id":"e_QkJ8a49xcq","version":"v0.1","op":"postgres.(Postgres).Run"},"datacontentype":"application/cloudevents","time":"2022-08-11T12:12:27.260748373+02:00"}
{"id":"UESUdcMi6l","source":"https://hashicorp.com/boundary/bastion01.prd.TLD/boundary-database-migrate","specversion":"1.0","type":"error","data":{"error":"postgres.(Postgres).setVersion: unknown, unknown: error #0: ERROR: current transaction is aborted, commands ignored until end of transaction block (SQLSTATE 25P02)","error_fields":{"Code":0,"Msg":"","Op":"postgres.(Postgres).setVersion","Wrapped":{"Severity":"ERROR","Code":"25P02","Message":"current transaction is aborted, commands ignored until end of transaction block","Detail":"","Hint":"","Position":0,"InternalPosition":0,"InternalQuery":"","Where":"","SchemaName":"","TableName":"","ColumnName":"","DataTypeName":"","ConstraintName":"","File":"postgres.c","Line":1682,"Routine":"exec_bind_message"}},"id":"e_aBY8cQsfUs","version":"v0.1","op":"postgres.(Postgres).setVersion"},"datacontentype":"application/cloudevents","time":"2022-08-11T12:12:27.261316739+02:00"}
{"id":"KvNQYjqHyf","source":"https://hashicorp.com/boundary/bastion01.prd.TLD/boundary-database-migrate","specversion":"1.0","type":"error","data":{"error":"postgres.(Postgres).Run: postgres.(Postgres).setVersion: unknown, unknown: error #0: ERROR: current transaction is aborted, commands ignored until end of transaction block (SQLSTATE 25P02)","error_fields":{"Code":0,"Msg":"","Op":"postgres.(Postgres).Run","Wrapped":{"Code":0,"Msg":"","Op":"postgres.(Postgres).setVersion","Wrapped":{"Severity":"ERROR","Code":"25P02","Message":"current transaction is aborted, commands ignored until end of transaction block","Detail":"","Hint":"","Position":0,"InternalPosition":0,"InternalQuery":"","Where":"","SchemaName":"","TableName":"","ColumnName":"","DataTypeName":"","ConstraintName":"","File":"postgres.c","Line":1682,"Routine":"exec_bind_message"}}},"id":"e_bCTn5FgDB7","version":"v0.1","op":"postgres.(Postgres).Run"},"datacontentype":"application/cloudevents","time":"2022-08-11T12:12:27.261424296+02:00"}
{"id":"GahOotjFvq","source":"https://hashicorp.com/boundary/bastion01.prd.TLD/boundary-database-migrate","specversion":"1.0","type":"error","data":{"error":"postgres.(Postgres).setVersion: unknown, unknown: error #0: ERROR: current transaction is aborted, commands ignored until end of transaction block (SQLSTATE 25P02)","error_fields":{"Code":0,"Msg":"","Op":"postgres.(Postgres).setVersion","Wrapped":{"Severity":"ERROR","Code":"25P02","Message":"current transaction is aborted, commands ignored until end of transaction block","Detail":"","Hint":"","Position":0,"InternalPosition":0,"InternalQuery":"","Where":"","SchemaName":"","TableName":"","ColumnName":"","DataTypeName":"","ConstraintName":"","File":"postgres.c","Line":1682,"Routine":"exec_bind_message"}},"id":"e_SEu1J9TTXn","version":"v0.1","op":"postgres.(Postgres).setVersion"},"datacontentype":"application/cloudevents","time":"2022-08-11T12:12:27.261976942+02:00"}
{"id":"8eAn8OrZ3r","source":"https://hashicorp.com/boundary/bastion01.prd.TLD/boundary-database-migrate","specversion":"1.0","type":"error","data":{"error":"postgres.(Postgres).Run: postgres.(Postgres).setVersion: unknown, unknown: error #0: ERROR: current transaction is aborted, commands ignored until end of transaction block (SQLSTATE 25P02)","error_fields":{"Code":0,"Msg":"","Op":"postgres.(Postgres).Run","Wrapped":{"Code":0,"Msg":"","Op":"postgres.(Postgres).setVersion","Wrapped":{"Severity":"ERROR","Code":"25P02","Message":"current transaction is aborted, commands ignored until end of transaction block","Detail":"","Hint":"","Position":0,"InternalPosition":0,"InternalQuery":"","Where":"","SchemaName":"","TableName":"","ColumnName":"","DataTypeName":"","ConstraintName":"","File":"postgres.c","Line":1682,"Routine":"exec_bind_message"}}},"id":"e_lZfs3GrCCq","version":"v0.1","op":"postgres.(Postgres).Run"},"datacontentype":"application/cloudevents","time":"2022-08-11T12:12:27.262075142+02:00"}
{"id":"D6o4CefzYs","source":"https://hashicorp.com/boundary/bastion01.prd.TLD/boundary-database-migrate","specversion":"1.0","type":"error","data":{"error":"postgres.(Postgres).CommitRun: unknown, unknown: error #0: commit unexpectedly resulted in rollback","error_fields":{"Code":0,"Msg":"","Op":"postgres.(Postgres).CommitRun","Wrapped":{}},"id":"e_o03IUjjptB","version":"v0.1","op":"postgres.(Postgres).CommitRun"},"datacontentype":"application/cloudevents","time":"2022-08-11T12:12:27.262512893+02:00"}
{"id":"USAzmI1SlQ","source":"https://hashicorp.com/boundary/bastion01.prd.TLD/boundary-database-migrate","specversion":"1.0","type":"error","data":{"error":"schema.(Manager).runMigrations: postgres.(Postgres).CommitRun: unknown, unknown: error #0: commit unexpectedly resulted in rollback","error_fields":{"Code":0,"Msg":"","Op":"schema.(Manager).runMigrations","Wrapped":{"Code":0,"Msg":"","Op":"postgres.(Postgres).CommitRun","Wrapped":{}}},"id":"e_K49SmgeJg9","version":"v0.1","op":"schema.(Manager).runMigrations"},"datacontentype":"application/cloudevents","time":"2022-08-11T12:12:27.262633846+02:00"}
{"id":"s2nSM2tcpB","source":"https://hashicorp.com/boundary/bastion01.prd.TLD/boundary-database-migrate","specversion":"1.0","type":"error","data":{"error":"schema.(Manager).ApplyMigrations: schema.(Manager).runMigrations: postgres.(Postgres).CommitRun: unknown, unknown: error #0: commit unexpectedly resulted in rollback","error_fields":{"Code":0,"Msg":"","Op":"schema.(Manager).ApplyMigrations","Wrapped":{"Code":0,"Msg":"","Op":"schema.(Manager).runMigrations","Wrapped":{"Code":0,"Msg":"","Op":"postgres.(Postgres).CommitRun","Wrapped":{}}}},"id":"e_BePmsLN7N2","version":"v0.1","op":"schema.(Manager).ApplyMigrations"},"datacontentype":"application/cloudevents","time":"2022-08-11T12:12:27.262714839+02:00"}
Error running database migrations: schema.(Manager).ApplyMigrations: schema.(Manager).runMigrations: postgres.(Postgres).CommitRun: unknown, unknown: error #0: commit unexpectedly resulted in rollback
```
i am able to revert to 0.91 and start the service but then replacing the binary with 0.10 i get the above again

**Comment by louisruch** [comment]
Hi @hijak,

Thanks for reporting this issue, we should have a fix out shortly in 0.10.1.

**Comment by louisruch** [comment]
@hijak 

`0.10.1` has been [released](https://www.boundaryproject.io/downloads), you should be able to migrate your cluster successfully now.

**Comment by hijak** [comment]
hi this seems to have wiped out my credential store info for a project

**Comment by tmessi** [comment]
Hi @hijak, I have been trying to investigate and recreate this. Is the credential store not showing in the UI and cli? Are you able to check the database directly. I am curious since there is also another [bug report about disappearing credentials stores](https://github.com/hashicorp/boundary/issues/2179) and I want to determine if this is related or not.

**Comment by hijak** [comment]
i wasnt able to check the cli for the issue but the store was gone from the ui... ive since added it back via the ui so im guessing it provisioned with a new id

what should i look for in the db?

**Comment by tmessi** [comment]
No worries. Similarly to [this comment](https://github.com/hashicorp/boundary/issues/2179#issuecomment-1199787404). I would expect to still see the old credential store in `credential_vault_store`, ie:

```sql
select public_id, scope_id, name, create_time, update_time, delete_time from credential_vault_store;
```

But that same entry would not show in the `credential_vault_store_public` view, ie:

```sql
select public_id, scope_id, name, create_time, update_time from credential_vault_store_public;
```

**Comment by hijak** [comment]
yes thats exactly whats going on
```boundary=# select public_id, scope_id, name, create_time, update_time, delete_time from credential_vault_store;
    public_id     |   scope_id   |    name    |          create_time          |          update_time          | delete_time 
------------------+--------------+------------+-------------------------------+-------------------------------+-------------
 csvlt_WMNFNFKJVT | p_dR982XXXXX | production | 2022-08-10 09:56:01.397248+00 | 2022-08-10 09:56:01.397248+00 | 
 csvlt_JzGTZXXXX | p_dR982XXXXX | Vault      | 2022-08-12 10:29:08.244826+00 | 2022-08-12 10:29:08.244826+00 | 
(2 rows)

boundary=# select public_id, scope_id, name, create_time, update_time from credential_vault_store_public;
    public_id     |   scope_id   | name  |          create_time          |          update_time          
------------------+--------------+-------+-------------------------------+-------------------------------
 csvlt_JzGTZXXXX | p_dR982XXXXX | Vault | 2022-08-12 10:29:08.244826+00 | 2022-08-12 10:29:08.244826+00
(1 row)```

**Comment by hijak** [comment]
seems like this is causes targets with the old credential store display an error when trying to connect not sure if its related
```targets.(Service).AuthorizeSession: vault.(Repository).Issue: vault.(privateLibrary).client: unable to create vault client: vault.newClient: invalid configuration: parameter violation: error #100```

**Comment by louisruch** [comment]
@hijak I was able to reproduce this issue locally and am working on a fix. 
Unfortunately, any libraries associated with the old credentials stores will no longer be able to Issue credentials since the token they use has expired. The bug also blocks you from updating the token on the old credential store so the only short term fix will be to create the libraries again. 
Sorry for the inconvenience, I will update this issue when a fix is in place.

**Comment by hijak** [comment]
how can i remove the old entry? as it seems targets still want to load this cred lib but error out

**Comment by EasyNV** [comment]
Hello, I also got database migration failed when upgrading from `0.10.1` to `0.10.2`

```
{"id":"TS2t5CmEa7","source":"https://hashicorp.com/boundary/boundary.prd.tld/boundary-database-migrate","specversion":"1.0","type":"system","data":{"version":"v0.1","op":"github.com/hashicorp/boundary/internal/observability/event.(*HclogLoggerAdapter).writeEvent","data":{"@original-log-level":"none","@original-log-name":"aws","msg":"configuring client automatic mTLS"}},"datacontentype":"application/cloudevents","time":"2022-08-29T08:31:35.913758818Z"}
{"id":"J8c8uGASJ7","source":"https://hashicorp.com/boundary/boundary.prd.tld/boundary-database-migrate","specversion":"1.0","type":"system","data":{"version":"v0.1","op":"github.com/hashicorp/boundary/internal/observability/event.(*HclogLoggerAdapter).writeEvent","data":{"@original-log-level":"none","@original-log-name":"aws","args":["/tmp/2420141639/boundary-plugin-host-aws-S7r4C"],"msg":"starting plugin","path":"/tmp/2420141639/boundary-plugin-host-aws-S7r4C"}},"datacontentype":"application/cloudevents","time":"2022-08-29T08:31:35.983626512Z"}
{"id":"0YrLykBfEj","source":"https://hashicorp.com/boundary/boundary.prd.tld/boundary-database-migrate","specversion":"1.0","type":"system","data":{"version":"v0.1","op":"github.com/hashicorp/boundary/internal/observability/event.(*HclogLoggerAdapter).writeEvent","data":{"@original-log-level":"none","@original-log-name":"aws","msg":"plugin started","path":"/tmp/2420141639/boundary-plugin-host-aws-S7r4C","pid":1949}},"datacontentype":"application/cloudevents","time":"2022-08-29T08:31:35.984877682Z"}
{"id":"kAjvHT9KCf","source":"https://hashicorp.com/boundary/boundary.prd.tld/boundary-database-migrate","specversion":"1.0","type":"system","data":{"version":"v0.1","op":"github.com/hashicorp/boundary/internal/observability/event.(*HclogLoggerAdapter).writeEvent","data":{"@original-log-level":"none","@original-log-name":"aws","msg":"waiting for RPC address","path":"/tmp/2420141639/boundary-plugin-host-aws-S7r4C"}},"datacontentype":"application/cloudevents","time":"2022-08-29T08:31:35.985066957Z"}
{"id":"dWSiSnVqvQ","source":"https://hashicorp.com/boundary/boundary.prd.tld/boundary-database-migrate","specversion":"1.0","type":"system","data":{"version":"v0.1","op":"github.com/hashicorp/boundary/internal/observability/event.(*HclogLoggerAdapter).writeEvent","data":{"@original-log-level":"none","@original-log-name":"aws.boundary-plugin-host-aws-S7r4C","msg":"configuring server automatic mTLS","timestamp":"2022-08-29T08:31:35.995Z"}},"datacontentype":"application/cloudevents","time":"2022-08-29T08:31:35.995268556Z"}
{"id":"eSDiwVtcvg","source":"https://hashicorp.com/boundary/boundary.prd.tld/boundary-database-migrate","specversion":"1.0","type":"system","data":{"version":"v0.1","op":"github.com/hashicorp/boundary/internal/observability/event.(*HclogLoggerAdapter).writeEvent","data":{"@original-log-level":"none","@original-log-name":"aws.boundary-plugin-host-aws-S7r4C","address":"/tmp/plugin2442192587","msg":"plugin address","network":"unix","timestamp":"2022-08-29T08:31:36.027Z"}},"datacontentype":"application/cloudevents","time":"2022-08-29T08:31:36.027474115Z"}
{"id":"cVFvkbXWNJ","source":"https://hashicorp.com/boundary/boundary.prd.tld/boundary-database-migrate","specversion":"1.0","type":"system","data":{"version":"v0.1","op":"github.com/hashicorp/boundary/internal/observability/event.(*HclogLoggerAdapter).writeEvent","data":{"@original-log-level":"none","@original-log-name":"aws","msg":"using plugin","version":1}},"datacontentype":"application/cloudevents","time":"2022-08-29T08:31:36.027521631Z"}
{"id":"y4maogros4","source":"https://hashicorp.com/boundary/boundary.prd.tld/boundary-database-migrate","specversion":"1.0","type":"system","data":{"version":"v0.1","op":"github.com/hashicorp/boundary/internal/observability/event.(*HclogLoggerAdapter).writeEvent","data":{"@original-log-level":"none","@original-log-name":"aws.stdio","msg":"waiting for stdio data"}},"datacontentype":"application/cloudevents","time":"2022-08-29T08:31:36.057118217Z"}
{"id":"lcJzHM3b9z","source":"https://hashicorp.com/boundary/boundary.prd.tld/boundary-database-migrate","specversion":"1.0","type":"system","data":{"version":"v0.1","op":"github.com/hashicorp/boundary/internal/observability/event.(*HclogLoggerAdapter).writeEvent","data":{"@original-log-level":"none","@original-log-name":"aws.stdio","err":{},"msg":"received EOF, stopping recv loop"}},"datacontentype":"application/cloudevents","time":"2022-08-29T08:31:36.057938616Z"}
{"id":"fRuYq6XOjs","source":"https://hashicorp.com/boundary/boundary.prd.tld/boundary-database-migrate","specversion":"1.0","type":"system","data":{"version":"v0.1","op":"github.com/hashicorp/boundary/internal/observability/event.(*HclogLoggerAdapter).writeEvent","data":{"@original-log-level":"none","@original-log-name":"aws","msg":"plugin process exited","path":"/tmp/2420141639/boundary-plugin-host-aws-S7r4C","pid":1949}},"datacontentype":"application/cloudevents","time":"2022-08-29T08:31:36.058995507Z"}
{"id":"wHQHPuYLMt","source":"https://hashicorp.com/boundary/boundary.prd.tld/boundary-database-migrate","specversion":"1.0","type":"system","data":{"version":"v0.1","op":"github.com/hashicorp/boundary/internal/observability/event.(*HclogLoggerAdapter).writeEvent","data":{"@original-log-level":"none","@original-log-name":"aws","msg":"plugin exited"}},"datacontentype":"application/cloudevents","time":"2022-08-29T08:31:36.059187533Z"}
{"id":"UzN4ioY0q9","source":"https://hashicorp.com/boundary/boundary.prd.tld/boundary-database-migrate","specversion":"1.0","type":"error","data":{"error":"postgres.(Postgres).Run: migration failed, on line 0: -- host_set\n  alter table host_set\n    add column project_id wt_public_id,\n    add constraint host_set_project_id_public_id_uq\n      unique(project_id, public_id)\n  ;\n\n  update host_set\n     set (project_id) =\n         (select project_id\n            from host_catalog\n           where host_catalog.public_id = host_set.catalog_id\n         )\n  ;\n\n  alter table host_set\n    alter column project_id set not null,\n    drop constraint host_catalog_fkey,\n    add constraint host_catalog_fkey\n      foreign key (project_id, catalog_id)\n        references host_catalog (project_id, public_id)\n        on delete cascade\n        on update cascade,\n    -- Replaces host_set_catalog_id_public_id_key\n    add constraint host_set_project_id_catalog_id_public_id_uq\n      unique(project_id, catalog_id, public_id)\n  ;\n\n  drop trigger immutable_columns on host_set;\n  create trigger immutable_columns before update on host_set\n    for each row execute function immutable_columns('public_id', 'catalog_id', 'project_id');\n\n  -- insert_host_set_subtype() is a before insert trigger\n  -- function for subtypes of host_set\n  -- Replaces the insert_host_set_subtype function defined in 0/20_host.up.sql\n  create or replace function insert_host_set_subtype() returns trigger\n  as $$\n  begin\n\n    select project_id into new.project_id\n      from host_catalog\n     where host_catalog.public_id = new.catalog_id;\n\n    insert into host_set\n      (public_id, catalog_id, project_id)\n    values\n      (new.public_id, new.catalog_id, new.project_id);\n    return new;\n  end;\n  $$ language plpgsql;\n\n-- static_host_set\n  alter table static_host_set\n    add column project_id wt_public_id\n  ;\n\n  update static_host_set\n     set (project_id) =\n         (select project_id\n            from host_set\n           where host_set.public_id = static_host_set.public_id\n         )\n  ;\n\n  alter table static_host_set\n    alter column project_id set not null,\n    add constraint host_set_fkey\n      foreign key (project_id, catalog_id, public_id)\n        references host_set (project_id, catalog_id, public_id)\n        on delete cascade\n        on update cascade,\n    drop constraint if exists static_host_set_catalog_id_fkey1, -- pg 11\n    drop constraint if exists static_host_set_catalog_id_public_id_fkey -- pg 12, 13, 14\n  ;\n\n  drop trigger immutable_columns on static_host_set;\n  create trigger immutable_columns before update on static_host_set\n    for each row execute procedure immutable_columns('public_id', 'catalog_id', 'project_id', 'create_time');\n\n-- host_plugin_set\n  alter table host_plugin_set\n    add column project_id wt_public_id\n  ;\n\n  update host_plugin_set\n     set (project_id) =\n         (select project_id\n            from host_set\n           where host_set.public_id = host_plugin_set.catalog_id\n         )\n  ;\n\n  alter table host_plugin_set\n    alter column project_id set not null,\n    drop constraint host_set_fkey,\n    add constraint host_set_fkey\n      foreign key (project_id, catalog_id, public_id)\n        references host_set (project_id, catalog_id, public_id)\n        on delete cascade\n        on update cascade\n  ;\n\n  drop trigger immutable_columns on host_plugin_set;\n  create trigger immutable_columns before update on host_plugin_set\n    for each row execute procedure immutable_columns('public_id', 'catalog_id', 'project_id', 'create_time');\n\n  alter table host_set\n    drop constraint host_set_catalog_id_public_id_key\n  ;: project_id must not be empty: not null constraint violated: integrity violation: error #1001","error_fields":{"Code":1001,"Msg":"migration failed, on line 0: -- host_set\n  alter table host_set\n    add column project_id wt_public_id,\n    add constraint host_set_project_id_public_id_uq\n      unique(project_id, public_id)\n  ;\n\n  update host_set\n     set (project_id) =\n         (select project_id\n            from host_catalog\n           where host_catalog.public_id = host_set.catalog_id\n         )\n  ;\n\n  alter table host_set\n    alter column project_id set not null,\n    drop constraint host_catalog_fkey,\n    add constraint host_catalog_fkey\n      foreign key (project_id, catalog_id)\n        references host_catalog (project_id, public_id)\n        on delete cascade\n        on update cascade,\n    -- Replaces host_set_catalog_id_public_id_key\n    add constraint host_set_project_id_catalog_id_public_id_uq\n      unique(project_id, catalog_id, public_id)\n  ;\n\n  drop trigger immutable_columns on host_set;\n  create trigger immutable_columns before update on host_set\n    for each row execute function immutable_columns('public_id', 'catalog_id', 'project_id');\n\n  -- insert_host_set_subtype() is a before insert trigger\n  -- function for subtypes of host_set\n  -- Replaces the insert_host_set_subtype function defined in 0/20_host.up.sql\n  create or replace function insert_host_set_subtype() returns trigger\n  as $$\n  begin\n\n    select project_id into new.project_id\n      from host_catalog\n     where host_catalog.public_id = new.catalog_id;\n\n    insert into host_set\n      (public_id, catalog_id, project_id)\n    values\n      (new.public_id, new.catalog_id, new.project_id);\n    return new;\n  end;\n  $$ language plpgsql;\n\n-- static_host_set\n  alter table static_host_set\n    add column project_id wt_public_id\n  ;\n\n  update static_host_set\n     set (project_id) =\n         (select project_id\n            from host_set\n           where host_set.public_id = static_host_set.public_id\n         )\n  ;\n\n  alter table static_host_set\n    alter column project_id set not null,\n    add constraint host_set_fkey\n      foreign key (project_id, catalog_id, public_id)\n        references host_set (project_id, catalog_id, public_id)\n        on delete cascade\n        on update cascade,\n    drop constraint if exists static_host_set_catalog_id_fkey1, -- pg 11\n    drop constraint if exists static_host_set_catalog_id_public_id_fkey -- pg 12, 13, 14\n  ;\n\n  drop trigger immutable_columns on static_host_set;\n  create trigger immutable_columns before update on static_host_set\n    for each row execute procedure immutable_columns('public_id', 'catalog_id', 'project_id', 'create_time');\n\n-- host_plugin_set\n  alter table host_plugin_set\n    add column project_id wt_public_id\n  ;\n\n  update host_plugin_set\n     set (project_id) =\n         (select project_id\n            from host_set\n           where host_set.public_id = host_plugin_set.catalog_id\n         )\n  ;\n\n  alter table host_plugin_set\n    alter column project_id set not null,\n    drop constraint host_set_fkey,\n    add constraint host_set_fkey\n      foreign key (project_id, catalog_id, public_id)\n        references host_set (project_id, catalog_id, public_id)\n        on delete cascade\n        on update cascade\n  ;\n\n  drop trigger immutable_columns on host_plugin_set;\n  create trigger immutable_columns before update on host_plugin_set\n    for each row execute procedure immutable_columns('public_id', 'catalog_id', 'project_id', 'create_time');\n\n  alter table host_set\n    drop constraint host_set_catalog_id_public_id_key\n  ;","Op":"postgres.(Postgres).Run","Wrapped":{"Code":1001,"Msg":"project_id must not be empty","Op":"","Wrapped":{"Code":1001,"Msg":"not null constraint violated","Op":"","Wrapped":null}}},"id":"e_30BnZHvfAP","version":"v0.1","op":"postgres.(Postgres).Run"},"datacontentype":"application/cloudevents","time":"2022-08-29T08:31:36.446549393Z"}
{"id":"1oLPYObCYA","source":"https://hashicorp.com/boundary/boundary.prd.tld/boundary-database-migrate","specversion":"1.0","type":"error","data":{"error":"schema.(Manager).runMigrations: postgres.(Postgres).Run: migration failed, on line 0: -- host_set\n  alter table host_set\n    add column project_id wt_public_id,\n    add constraint host_set_project_id_public_id_uq\n      unique(project_id, public_id)\n  ;\n\n  update host_set\n     set (project_id) =\n         (select project_id\n            from host_catalog\n           where host_catalog.public_id = host_set.catalog_id\n         )\n  ;\n\n  alter table host_set\n    alter column project_id set not null,\n    drop constraint host_catalog_fkey,\n    add constraint host_catalog_fkey\n      foreign key (project_id, catalog_id)\n        references host_catalog (project_id, public_id)\n        on delete cascade\n        on update cascade,\n    -- Replaces host_set_catalog_id_public_id_key\n    add constraint host_set_project_id_catalog_id_public_id_uq\n      unique(project_id, catalog_id, public_id)\n  ;\n\n  drop trigger immutable_columns on host_set;\n  create trigger immutable_columns before update on host_set\n    for each row execute function immutable_columns('public_id', 'catalog_id', 'project_id');\n\n  -- insert_host_set_subtype() is a before insert trigger\n  -- function for subtypes of host_set\n  -- Replaces the insert_host_set_subtype function defined in 0/20_host.up.sql\n  create or replace function insert_host_set_subtype() returns trigger\n  as $$\n  begin\n\n    select project_id into new.project_id\n      from host_catalog\n     where host_catalog.public_id = new.catalog_id;\n\n    insert into host_set\n      (public_id, catalog_id, project_id)\n    values\n      (new.public_id, new.catalog_id, new.project_id);\n    return new;\n  end;\n  $$ language plpgsql;\n\n-- static_host_set\n  alter table static_host_set\n    add column project_id wt_public_id\n  ;\n\n  update static_host_set\n     set (project_id) =\n         (select project_id\n            from host_set\n           where host_set.public_id = static_host_set.public_id\n         )\n  ;\n\n  alter table static_host_set\n    alter column project_id set not null,\n    add constraint host_set_fkey\n      foreign key (project_id, catalog_id, public_id)\n        references host_set (project_id, catalog_id, public_id)\n        on delete cascade\n        on update cascade,\n    drop constraint if exists static_host_set_catalog_id_fkey1, -- pg 11\n    drop constraint if exists static_host_set_catalog_id_public_id_fkey -- pg 12, 13, 14\n  ;\n\n  drop trigger immutable_columns on static_host_set;\n  create trigger immutable_columns before update on static_host_set\n    for each row execute procedure immutable_columns('public_id', 'catalog_id', 'project_id', 'create_time');\n\n-- host_plugin_set\n  alter table host_plugin_set\n    add column project_id wt_public_id\n  ;\n\n  update host_plugin_set\n     set (project_id) =\n         (select project_id\n            from host_set\n           where host_set.public_id = host_plugin_set.catalog_id\n         )\n  ;\n\n  alter table host_plugin_set\n    alter column project_id set not null,\n    drop constraint host_set_fkey,\n    add constraint host_set_fkey\n      foreign key (project_id, catalog_id, public_id)\n        references host_set (project_id, catalog_id, public_id)\n        on delete cascade\n        on update cascade\n  ;\n\n  drop trigger immutable_columns on host_plugin_set;\n  create trigger immutable_columns before update on host_plugin_set\n    for each row execute procedure immutable_columns('public_id', 'catalog_id', 'project_id', 'create_time');\n\n  alter table host_set\n    drop constraint host_set_catalog_id_public_id_key\n  ;: project_id must not be empty: not null constraint violated: integrity violation: error #1001","error_fields":{"Code":1001,"Msg":"","Op":"schema.(Manager).runMigrations","Wrapped":{"Code":1001,"Msg":"migration failed, on line 0: -- host_set\n  alter table host_set\n    add column project_id wt_public_id,\n    add constraint host_set_project_id_public_id_uq\n      unique(project_id, public_id)\n  ;\n\n  update host_set\n     set (project_id) =\n         (select project_id\n            from host_catalog\n           where host_catalog.public_id = host_set.catalog_id\n         )\n  ;\n\n  alter table host_set\n    alter column project_id set not null,\n    drop constraint host_catalog_fkey,\n    add constraint host_catalog_fkey\n      foreign key (project_id, catalog_id)\n        references host_catalog (project_id, public_id)\n        on delete cascade\n        on update cascade,\n    -- Replaces host_set_catalog_id_public_id_key\n    add constraint host_set_project_id_catalog_id_public_id_uq\n      unique(project_id, catalog_id, public_id)\n  ;\n\n  drop trigger immutable_columns on host_set;\n  create trigger immutable_columns before update on host_set\n    for each row execute function immutable_columns('public_id', 'catalog_id', 'project_id');\n\n  -- insert_host_set_subtype() is a before insert trigger\n  -- function for subtypes of host_set\n  -- Replaces the insert_host_set_subtype function defined in 0/20_host.up.sql\n  create or replace function insert_host_set_subtype() returns trigger\n  as $$\n  begin\n\n    select project_id into new.project_id\n      from host_catalog\n     where host_catalog.public_id = new.catalog_id;\n\n    insert into host_set\n      (public_id, catalog_id, project_id)\n    values\n      (new.public_id, new.catalog_id, new.project_id);\n    return new;\n  end;\n  $$ language plpgsql;\n\n-- static_host_set\n  alter table static_host_set\n    add column project_id wt_public_id\n  ;\n\n  update static_host_set\n     set (project_id) =\n         (select project_id\n            from host_set\n           where host_set.public_id = static_host_set.public_id\n         )\n  ;\n\n  alter table static_host_set\n    alter column project_id set not null,\n    add constraint host_set_fkey\n      foreign key (project_id, catalog_id, public_id)\n        references host_set (project_id, catalog_id, public_id)\n        on delete cascade\n        on update cascade,\n    drop constraint if exists static_host_set_catalog_id_fkey1, -- pg 11\n    drop constraint if exists static_host_set_catalog_id_public_id_fkey -- pg 12, 13, 14\n  ;\n\n  drop trigger immutable_columns on static_host_set;\n  create trigger immutable_columns before update on static_host_set\n    for each row execute procedure immutable_columns('public_id', 'catalog_id', 'project_id', 'create_time');\n\n-- host_plugin_set\n  alter table host_plugin_set\n    add column project_id wt_public_id\n  ;\n\n  update host_plugin_set\n     set (project_id) =\n         (select project_id\n            from host_set\n           where host_set.public_id = host_plugin_set.catalog_id\n         )\n  ;\n\n  alter table host_plugin_set\n    alter column project_id set not null,\n    drop constraint host_set_fkey,\n    add constraint host_set_fkey\n      foreign key (project_id, catalog_id, public_id)\n        references host_set (project_id, catalog_id, public_id)\n        on delete cascade\n        on update cascade\n  ;\n\n  drop trigger immutable_columns on host_plugin_set;\n  create trigger immutable_columns before update on host_plugin_set\n    for each row execute procedure immutable_columns('public_id', 'catalog_id', 'project_id', 'create_time');\n\n  alter table host_set\n    drop constraint host_set_catalog_id_public_id_key\n  ;","Op":"postgres.(Postgres).Run","Wrapped":{"Code":1001,"Msg":"project_id must not be empty","Op":"","Wrapped":{"Code":1001,"Msg":"not null constraint violated","Op":"","Wrapped":null}}}},"id":"e_jUEzELAWwy","version":"v0.1","op":"schema.(Manager).runMigrations"},"datacontentype":"application/cloudevents","time":"2022-08-29T08:31:36.446945196Z"}
{"id":"XAEGD96QFW","source":"https://hashicorp.com/boundary/boundary.prd.tld/boundary-database-migrate","specversion":"1.0","type":"error","data":{"error":"postgres.(Postgres).CommitRun: unknown, unknown: error #0: commit unexpectedly resulted in rollback","error_fields":{"Code":0,"Msg":"","Op":"postgres.(Postgres).CommitRun","Wrapped":{}},"id":"e_Der8J1WJoU","version":"v0.1","op":"postgres.(Postgres).CommitRun"},"datacontentype":"application/cloudevents","time":"2022-08-29T08:31:36.447917142Z"}
{"id":"fZuMgtXeY2","source":"https://hashicorp.com/boundary/boundary.prd.tld/boundary-database-migrate","specversion":"1.0","type":"error","data":{"error":"schema.(Manager).runMigrations: postgres.(Postgres).CommitRun: unknown, unknown: error #0: commit unexpectedly resulted in rollback","error_fields":{"Code":0,"Msg":"","Op":"schema.(Manager).runMigrations","Wrapped":{"Code":0,"Msg":"","Op":"postgres.(Postgres).CommitRun","Wrapped":{}}},"id":"e_NXuglOQBGp","version":"v0.1","op":"schema.(Manager).runMigrations"},"datacontentype":"application/cloudevents","time":"2022-08-29T08:31:36.448023998Z"}
Error running database migrations: schema.(Manager).runMigrations: postgres.(Postgres).Run: migration failed, on line 0: -- host_set
  alter table host_set
    add column project_id wt_public_id,
    add constraint host_set_project_id_public_id_uq
      unique(project_id, public_id)
  ;

  update host_set
     set (project_id) =
         (select project_id
            from host_catalog
           where host_catalog.public_id = host_set.catalog_id
         )
  ;

  alter table host_set
    alter column project_id set not null,
    drop constraint host_catalog_fkey,
    add constraint host_catalog_fkey
      foreign key (project_id, catalog_id)
        references host_catalog (project_id, public_id)
        on delete cascade
        on update cascade,
    -- Replaces host_set_catalog_id_public_id_key
    add constraint host_set_project_id_catalog_id_public_id_uq
      unique(project_id, catalog_id, public_id)
  ;

  drop trigger immutable_columns on host_set;
  create trigger immutable_columns before update on host_set
    for each row execute function immutable_columns('public_id', 'catalog_id', 'project_id');

  -- insert_host_set_subtype() is a before insert trigger
  -- function for subtypes of host_set
  -- Replaces the insert_host_set_subtype function defined in 0/20_host.up.sql
  create or replace function insert_host_set_subtype() returns trigger
  as $$
  begin

    select project_id into new.project_id
      from host_catalog
     where host_catalog.public_id = new.catalog_id;

    insert into host_set
      (public_id, catalog_id, project_id)
    values
      (new.public_id, new.catalog_id, new.project_id);
    return new;
  end;
  $$ language plpgsql;

-- static_host_set
  alter table static_host_set
    add column project_id wt_public_id
  ;

  update static_host_set
     set (project_id) =
         (select project_id
            from host_set
           where host_set.public_id = static_host_set.public_id
         )
  ;

  alter table static_host_set
    alter column project_id set not null,
    add constraint host_set_fkey
      foreign key (project_id, catalog_id, public_id)
        references host_set (project_id, catalog_id, public_id)
        on delete cascade
        on update cascade,
    drop constraint if exists static_host_set_catalog_id_fkey1, -- pg 11
    drop constraint if exists static_host_set_catalog_id_public_id_fkey -- pg 12, 13, 14
  ;

  drop trigger immutable_columns on static_host_set;
  create trigger immutable_columns before update on static_host_set
    for each row execute procedure immutable_columns('public_id', 'catalog_id', 'project_id', 'create_time');

-- host_plugin_set
  alter table host_plugin_set
    add column project_id wt_public_id
  ;

  update host_plugin_set
     set (project_id) =
         (select project_id
            from host_set
           where host_set.public_id = host_plugin_set.catalog_id
         )
  ;

  alter table host_plugin_set
    alter column project_id set not null,
    drop constraint host_set_fkey,
    add constraint host_set_fkey
      foreign key (project_id, catalog_id, public_id)
        references host_set (project_id, catalog_id, public_id)
        on delete cascade
        on update cascade
  ;

  drop trigger immutable_columns on host_plugin_set;
  create trigger immutable_columns before update on host_plugin_set
    for each row execute procedure immutable_columns('public_id', 'catalog_id', 'project_id', 'create_time');

  alter table host_set
    drop constraint host_set_catalog_id_public_id_key
  ;: project_id must not be empty: not null constraint violated: integrity violation: error #1001
```

**Comment by ddebko** [comment]
@EasyNV We have deployed a fix for your issue, please try the latest release 0.10.3 and please let us know if everything went smoothly.

**Comment by EasyNV** [comment]
> @EasyNV We have cut a release to solve the issue you have found, please try the latest release 0.10.3 and please let us know if everything went smoothly.

Thanks a lot! Version `0.10.3` fixed the db migration issue! 😄

**Comment by hijak** [comment]
i still get ```Error

targets.(Service).AuthorizeSession: vault.(Repository).Issue: vault.(privateLibrary).client: unable to create vault client: vault.newClient: invalid configuration: parameter violation: error #100

Would you like to retry?```
when trying to connect with a target with cred store from previous version... i guess ill just start again
