### ISSUE TITLE
Boundary Desktop Loading Times

### ISSUE THREAD

**Issue by Lukas-Siegle** [hashicorp/boundary#4910]
When using Boundary Desktop, loading times to list targets and sessions are unusually slow. In contrast, using the CLI results in significantly faster loading times. This issue occurs on both our production cluster and a dev instance.

### To Reproduce

1. **Start a dev server:**
   - Run `boundary dev`
2. **Check Latency:**
   - List targets using the CLI: `boundary targets list -recursive` → almost instant response.
   - Open Boundary Desktop, connect to the dev cluster, and observe the waiting times. 

### Expected Behavior

Boundary Desktop should have acceptable waiting times, as it is very painful to wait several seconds for the targets to load.

**Comment by calcaide** [comment]
Hi @Lukas-Siegle  thank you for using Boundary and reporting this.

Can you share what version of Boundary controller and what version of the Boundary desktop client are you running?

Thank you.

**Comment by Lukas-Siegle** [comment]
The versions I specifically tested are the most recent ones:

- Desktop Client: 2.0.3
- Controller: 0.16.2

The problem also appeared in earlier versions, but I don't know exactly which ones. I think when I used Boundary 0.13 with the latest desktop client for that version, the issue did not exist. However, I cannot pinpoint exactly when the problem started for us, as we only started using Boundary in production some time ago.

**Comment by calcaide** [comment]
Thanks for the information @Lukas-Siegle 

What operating system are you running the desktop client?

More or less, how many targets do you have on that environment?

When you mention "loading times to list targets and sessions are unusually slow" how slow are we talking about? asking to have a reference.

Yeah, within the latest versions we have been detecting some slow load times and we have fix them on the latest desktop client version `2.0.3`. Mentioning this for the issues you mentioned in earlier versions, so you got some context.

**Comment by Lukas-Siegle** [comment]
I'm using Boundary Desktop on Windows 11 Pro. We recently went into production with the cluster, and there are not many targets yet—just 3 orgs with a total of about 10 targets. Therefore, there shouldn't be any extra loading time due to the controller handling large amounts of data. In the dev cluster, there are about 5 targets. As previously mentioned, we don't have any loading time issues on the CLI, so the problem seems to lie within the Desktop app. Slow responses from the database to the controller to the user don't appear to be the issue. There was already an issue with similar traits, but I believe it is fixed already #3281.

**Comment by Lukas-Siegle** [comment]
I measured the loading times several times, and even on the local dev cluster, it took between 7-10 seconds, while the CLI response was less than 0.5 seconds. Loading times on the dev cluster were similar to the prod cluster.

**Comment by calcaide** [comment]
@Lukas-Siegle 

Definitely 7-10 seconds is way more than expected.

I am unable to reproduce the issue with the versions you are using.

A possible issue is that the daemon cache running on your system is failing for some reason.
With the `boundary dev` running and the DC connected to the boundary dev instance, can you run the command `boundary daemon status` and see what that brings back ?

Thank you

**Comment by Lukas-Siegle** [comment]
Sure: 

![image](https://github.com/hashicorp/boundary/assets/166910541/ea226d2f-5362-430d-a43c-c2aa48f4775c)

**Comment by lisbet-alvarez** [comment]
@Lukas-Siegle Thank you for the new info.

Yes, the outdated daemon version could be the issue. Furthermore, there was a bug in the daemon affecting load speeds that was fixed in [boundary 0.15.3](https://github.com/hashicorp/boundary/releases/tag/v0.15.3). I recommend using the cmd `boundary daemon stop` then using `boundary daemon start` so that the daemon starts up again with the correct version (validate info. w/ `boundary daemon status`). Let us know if updating resolves the slow loading issue.

**Comment by Lukas-Siegle** [comment]
Unfortunately, that did not resolve the issue for either the dev or prod cluster. Here are the logs from the boundary daemon during the refresh of Sessions and Targets, though I didn't notice anything unusual.

```cache.log
2024-07-02T08:33:52.613+0200 [INFO]  system event: version=v0.1 op="cache.(Repository).refreshSessions" data:deleted=0 data:upserted=0 data:user_id=u_1234567890 data:msg="sessions updated"
2024-07-02T08:34:06.462+0200 [INFO]  system event: version=v0.1 op="cache.(Repository).refreshResolvableAliases" data:deleted=0 data:upserted=0 data:user_id=u_1234567890 data:msg="resolvable-aliases updated"
2024-07-02T08:34:08.618+0200 [INFO]  system event: op="cache.(Repository).refreshSessions" data:user_id=u_1234567890 data:msg="sessions updated" data:deleted=0 data:upserted=0 version=v0.1
2024-07-02T08:34:13.018+0200 [INFO]  system event: version=v0.1 op="cache.(Repository).refreshResolvableAliases" data:user_id=u_vsAfdKBnKI data:msg="resolvable-aliases updated" data:deleted=0 data:upserted=0
2024-07-02T08:34:13.064+0200 [INFO]  system event: version=v0.1 op="cache.(Repository).refreshTargets" data:deleted=0 data:upserted=0 data:user_id=u_1234567890 data:msg="targets updated"
2024-07-02T08:34:13.125+0200 [INFO]  system event: version=v0.1 op="cache.(Repository).refreshTargets" data:deleted=0 data:upserted=0 data:user_id=u_vsAfdKBnKI data:msg="targets updated"
2024-07-02T08:34:16.293+0200 [INFO]  system event: version=v0.1 op="cache.(Repository).refreshSessions" data:msg="sessions updated" data:deleted=0 data:upserted=0 data:user_id=u_vsAfdKBnKI
2024-07-02T08:34:16.330+0200 [INFO]  system event: data:deleted=0 data:upserted=0 data:user_id=u_1234567890 data:msg="resolvable-aliases updated" version=v0.1 op="cache.(Repository).refreshResolvableAliases"
2024-07-02T08:34:16.358+0200 [INFO]  system event: version=v0.1 op="cache.(Repository).refreshTargets" data:msg="targets updated" data:deleted=0 data:upserted=0 data:user_id=u_1234567890
2024-07-02T08:34:16.384+0200 [INFO]  system event: data:deleted=0 data:upserted=0 data:user_id=u_1234567890 data:msg="sessions updated" version=v0.1 op="cache.(Repository).refreshSessions"
2024-07-02T08:35:13.682+0200 [INFO]  system event: version=v0.1 op="cache.(Repository).refreshTargets" data:deleted=0 data:upserted=0 data:user_id=u_1234567890 data:msg="targets updated"
2024-07-02T08:35:25.855+0200 [INFO]  system event: version=v0.1 op="cache.(Repository).refreshResolvableAliases" data:msg="resolvable-aliases updated" data:deleted=0 data:upserted=0 data:user_id=u_1234567890
2024-07-02T08:35:28.362+0200 [INFO]  system event: version=v0.1 op="cache.(Repository).refreshSessions" data:deleted=0 data:upserted=0 data:user_id=u_1234567890 data:msg="sessions updated"
2024-07-02T08:35:33.601+0200 [INFO]  system event: version=v0.1 op="cache.(Repository).refreshTargets" data:upserted=0 data:user_id=u_1234567890 data:msg="targets updated" data:deleted=0

```

![image](https://github.com/hashicorp/boundary/assets/166910541/9dae661c-1f2a-4d60-a4b4-585647298895)

**Comment by Lukas-Siegle** [comment]
I just installed Boundary Desktop on a clean Windows 11 Home. The loading times for the dev (local) and prod (remote) cluster are around 2 seconds, which is much better than on my other machine. It seems old dependencies might be slowing it down. Are 2 seconds similar to your loading times?

**Comment by lisbet-alvarez** [comment]
Yes, 1-3 seconds is the range we are used to seeing in loading times. Though, I am curious as to what specifically was causing the slowness in your Windows 11 Pro setup. We will keep an eye out for that since we test using Windows 11 Pro in Parallels.

**Comment by Lukas-Siegle** [comment]
Okay, thank you very much 👍
